### ISSUE TITLE
Could I use this tool for memory leak?

### ISSUE THREAD

**Issue by kocoten1992** [sj-i/php-profiler#271]
Hi maintainer,

I'm exploring this tool, could this tool be use for memory leak checking? I've try:

```bash
./reli inspector:trace -p <pid>
```

But it doesn't seem to show anything related to memory, is this is for cpu profiler only?

**Comment by sj-i** [comment]
@kocoten1992 
Hi!

Unfortunately, this tool cannot be used to track memory usage. It probably won't work for that purpose in the future too, because of the similar reasons described in the following article.
https://tideways.com/profiler/blog/the-difficulty-of-memory-profiling-in-php 

I'm having an idea of another tool to investigate memory bottlenecks using a mechanism similar to reli.

But currently I don't have much time, so it doesn't look like I'll be able to make it soon...

If you have an option to install an extension, and having some performance overhead is allowed, you can try php-memprof.
https://github.com/arnaud-lb/php-memory-profiler

**Comment by kocoten1992** [comment]
thank you for explaining!

**Comment by sj-i** [comment]
@kocoten1992 
Once I wrote it as above, but on second thoughts, I ended up implementing it as an additional feature of reli.
Because now I don't have the time to manage the memory profiler as a separate project, while also cutting out the common code with reli and making that also in a separate package.

So, now it is possible to detect memory leaks with reli!
https://github.com/reliforp/reli-prof/blob/0.11.x/docs/memory-profiler.md

**Comment by kocoten1992** [comment]
This is huge!

I think the average user will use `apt-get` or similar to install php, and in my experience, that does not play well with pecl, for example: on debian/ubuntu, thanks to the work of `ondrej`, install php is easy, but when introduce pecl, most package over there are not maintained, when new php version come out, compatibility is a question...

I'd go as far as saying: unless org manually build php from the ground up, pecl is a no-go for anyone else involve, so that eliminate most of current php memory profile repo.

Do you post this on ycombinator or reddit yet? This is huge!

**Comment by sj-i** [comment]
Thanks!

Using pecl is not that hard. I don't know if enabling FFI is an easy choice for the average user, though there is also an option to use reli in docker.

Anyway, I believe this memory profiler is not bad compared to the memory profiling features in other extensions currently available.

With reli, it is possible to find where the leaks are. And with php-memprof, you can find out when the leaks occurred. These are complementary to each other.

I posted this on both HN Show and Reddit, and didn't get so many tractions. Though it [seems](https://blog.jetbrains.com/phpstorm/2023/12/php-annotated-november-2023/#tools) that at least it reaches Mr. Pronskiy at JetBrains.

- https://www.reddit.com/r/PHP/comments/182dzr4/reli_090_is_released_with_a_memory_profiling_tool/
- https://news.ycombinator.com/item?id=38399072
